from __future__ import annotations
from .data_types import TokenPolicy, RankingParams, Columns

def default_columns() -> Columns:
    return Columns()

def default_token_policy() -> TokenPolicy:
    forced = (
        ("autistic", "trait"),
        ("mental", "health"),
        ("autism", "spectrum", "disorder"),
        ("autism", "spectrum", "condition"),
        ("camouflage", "behavior"),
        ("camouflaging", "behavior"),
        ("self", "report"),
        ("autistic", "identity"),
        ("social", "anxiety"),
        ("well", "being"),
        ("well", "be"),
        ("impression", "management"),
        ("autistic", "characteristic"),
        ("quality", "of", "life"),
        ("generalize", "anxiety"),
        ("perceive", "stress"),
        ("internal", "consistency"),
        ("compensatory", "strategy"),
        ("social", "relationship"),
        ("typically", "develop"),
        ("typically", "developing"),
        ("self", "perceive"),
        ("thematic", "analysis"),
        ("general", "population"),
        ("first", "impression"),
        ("social", "context"),
        ("social", "skill"),
        ("social", "interaction"),
        ("social", "communication"),
        ("autism", "trait"),
        ("construct", "validity"),
        ("autistic", "community"),
        ("social", "strategy"),
        ("clinical", "practice"), 
        ("systematic", "review"), 
        ("symptom", "severity"),
        ("risk", "factor"),
        ("fear", "of", "negative", "evaluation"),
        ("intellectual", "disability"),
        ("social", "environment"),
        ("measurement", "invariance"),
        ("minority", "stress"),
        ("social", "motivation"),
        ("convergent", "validity"),
        ("coping", "strategy"),
        ("cope", "strategy"),
        ("interaction", "effect"),
        ("social", "challenge"),
        ("eating", "disorder"),
        ("theory", "of", "mind"),
        ("open", "end"),
        ("live", "experience"),
        ("co", "occur"),
        ("co", "occurring"),
        ("gender", "diverse"),
        ("posttraumatic", "stress"),
        ("social", "norm"),
        ("mediation", "analysis"),
        ("mediation", "analyzes"), # analysesの誤変換
        ("mix", "method"),
        ("neurodivergent","trait"),
        ("executive", "function"),
        ("general", "education"),
        ("perceive", "stigma"),
        ("sensory", "processing"),
        ("sensory", "process"),
        ("interpersonal", "trauma"),
        ("internalize", "stigma"),
        ("cognitive", "flexibility"),
        ("compensatory", "behavior"),

        ("social", "camouflage"),
        ("social", "camouflaging"),
    )

    return TokenPolicy(
        target_pos=frozenset({"NOUN", "VERB", "ADJ", "ADV"}),
        exclude_ner=frozenset({"PERSON", "GPE", "LOC"}),
        exclude_propn=True,
        exclude_aux=True,
        keep_surface_for=frozenset(),
        forced_phrases=forced,
        forced_joiner="_",
    )

def default_ranking_params() -> RankingParams:
    return RankingParams(top_n=50, min_docs=1)
